// 准备阶段：生成 puppeteer 用例文件骨架
// live 模式下注入 __step__ / __loop__ / __emit__ 帮助函数，
// 让子进程按步截图并把事件通过 stdout 写出（live runner 解析后推 WS）
//
// 这一份是从原 server/src/translator/prepare.js 移植到 TS，
// 行为完全一致，不引入新的运行语义

import * as fs from 'node:fs';

function detectChromePath(): string | undefined {
  const candidates = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium',
  ];
  return candidates.find((p) => {
    try {
      fs.accessSync(p);
      return true;
    } catch {
      return false;
    }
  });
}

function sanitizeName(s: string): string {
  return String(s ?? 'untitled')
    .replace(/[^\w\u4e00-\u9fa5\-]+/g, '_')
    .slice(0, 80);
}

export interface PrepareOpts {
  live?: boolean;
}

export function prepare(caseName: string, opts: PrepareOpts = {}): string {
  const live = !!opts.live;
  const safeName = sanitizeName(caseName);
  const chromePath = detectChromePath();
  const launchOpts: Record<string, unknown> = {
    headless: true,
    defaultViewport: { width: 1280, height: 800 },
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  };
  if (chromePath) launchOpts.executablePath = chromePath;

  const liveHelpers = live
    ? `
// ====== LIVE HELPERS ======
const __emit__ = (obj) => {
  try { process.stdout.write('__EVT__' + JSON.stringify(obj) + '\\n'); } catch {}
};
let __lastShot__ = 0;
async function __shoot__(page) {
  const now = Date.now();
  if (now - __lastShot__ < 80) await new Promise(r => setTimeout(r, 80 - (now - __lastShot__)));
  __lastShot__ = Date.now();
  try {
    return await page.screenshot({ encoding: 'base64', type: 'jpeg', quality: 55 });
  } catch (e) {
    __emit__({ type: 'log', level: 'stderr', text: '[__shoot__] ' + (e && e.message) });
    return null;
  }
}
let __stepIdx__ = 0;
async function __step__(page, name, fn) {
  __emit__({ type: 'step-start', name, index: __stepIdx__ });
  const t0 = Date.now();
  try {
    const result = await fn();
    const shot = await __shoot__(page);
    __emit__({ type: 'step-end', name, index: __stepIdx__, duration: Date.now() - t0, screenshot: shot, ok: true });
    return result;
  } catch (err) {
    const shot = await __shoot__(page);
    __emit__({ type: 'step-end', name, index: __stepIdx__, duration: Date.now() - t0, screenshot: shot, ok: false, error: err && err.message });
    throw err;
  } finally { __stepIdx__++; }
}
async function __loop__(page, name, count, fn) {
  __emit__({ type: 'step-start', name, index: __stepIdx__, loop: { count } });
  const t0 = Date.now();
  try {
    const result = await fn();
    const shot = await __shoot__(page);
    __emit__({ type: 'step-end', name, index: __stepIdx__, duration: Date.now() - t0, screenshot: shot, ok: true });
    return result;
  } catch (err) {
    const shot = await __shoot__(page);
    __emit__({ type: 'step-end', name, index: __stepIdx__, duration: Date.now() - t0, screenshot: shot, ok: false, error: err && err.message });
    throw err;
  } finally { __stepIdx__++; }
}
`
    : '';

  return `// AUTO-GENERATED by E2E Orchestrator${live ? ' (LIVE PREVIEW)' : ''}
// Case: ${safeName}
// Generated at: ${new Date().toISOString()}

const puppeteer = require('puppeteer');
${liveHelpers}

describe(${JSON.stringify(safeName)}, () => {
  let browser;
  let page;

  beforeAll(async () => {
    browser = await puppeteer.launch(${JSON.stringify(launchOpts)});
    page = await browser.newPage();
    page.setDefaultTimeout(30000);
    page.on('console', (msg) => {
      const type = msg.type();
      if (type === 'error' || type === 'warning') {
        console.log('[browser:' + type + ']', msg.text());
      }
    });
    page.on('pageerror', (err) => console.log('[browser:pageerror]', err.message));
  });

  afterAll(async () => {
    if (browser) await browser.close();
  });

  it('runs end-to-end', async () => {
    const start = Date.now();
    try {
__BODY__
      console.log('[case] done in ' + (Date.now() - start) + 'ms');
    } catch (err) {
      console.log('[case] failed:', err && err.message);
      throw err;
    }
  });
});
`;
}
