// 准备阶段：生成 puppeteer 用例文件骨架
// 骨架包含：imports、describe/it 容器、page 生命周期、通用 helpers
// 解析阶段产出的 body 字符串会填充到 __BODY__ 标记处
//
// live 模式下会额外注入 __step__ / __loop__ / __emit__ 帮助函数，
// 让子进程按步截图并把事件通过 stdout 写出（live runner 解析后推 WS）

import fs from 'node:fs';

// 自动检测系统已安装的 Chrome 路径
function detectChromePath() {
  const candidates = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium',
  ];
  return candidates.find((p) => {
    try { fs.accessSync(p); return true; } catch { return false; }
  });
}

export function prepare(caseName, opts = {}) {
  const live = !!opts.live;
  const safeName = sanitizeName(caseName);
  const chromePath = detectChromePath();
  const launchOpts = {
    headless: true,
    // Puppeteer 23 移除了 page.setDefaultViewport()，必须在这里设
    defaultViewport: { width: 1280, height: 800 },
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  };
  if (chromePath) launchOpts.executablePath = chromePath;

  // live 模式：__emit__ 通过 stdout 写出 __EVT__{json}\n 事件
  // __step__ / __loop__ 包装操作并在执行后截图
  const liveHelpers = live
    ? `
// ====== LIVE HELPERS ======
// 通过 stdout 输出事件（line-prefix 协议），外层进程解析后推 WS
const __emit__ = (obj) => {
  try { process.stdout.write('__EVT__' + JSON.stringify(obj) + '\\n'); } catch {}
};
// 限流：相邻两次截图至少间隔 80ms，避免快速连点刷爆 WS
let __lastShot__ = 0;
async function __shoot__(page) {
  const now = Date.now();
  if (now - __lastShot__ < 80) await new Promise(r => setTimeout(r, 80 - (now - __lastShot__)));
  __lastShot__ = Date.now();
  try {
    const buf = await page.screenshot({ encoding: 'base64', type: 'jpeg', quality: 55 });
    return buf;
  } catch (e) {
    __emit__({ type: 'log', level: 'stderr', text: '[__shoot__] ' + (e && e.message) });
    return null;
  }
}
let __stepIdx__ = 0;
async function __step__(page, name, fn) {
  __emit__({ type: 'step-start', name, index: __stepIdx__ });
  const t0 = Date.now();
  try {
    const result = await fn();
    const shot = await __shoot__(page);
    __emit__({
      type: 'step-end',
      name,
      index: __stepIdx__,
      duration: Date.now() - t0,
      screenshot: shot,
      ok: true,
    });
    return result;
  } catch (err) {
    const shot = await __shoot__(page);
    __emit__({
      type: 'step-end',
      name,
      index: __stepIdx__,
      duration: Date.now() - t0,
      screenshot: shot,
      ok: false,
      error: err && err.message,
    });
    throw err;
  } finally {
    __stepIdx__++;
  }
}
async function __loop__(page, name, count, fn) {
  __emit__({ type: 'step-start', name, index: __stepIdx__, loop: { count } });
  const t0 = Date.now();
  try {
    const result = await fn();
    const shot = await __shoot__(page);
    __emit__({
      type: 'step-end',
      name,
      index: __stepIdx__,
      duration: Date.now() - t0,
      screenshot: shot,
      ok: true,
    });
    return result;
  } catch (err) {
    const shot = await __shoot__(page);
    __emit__({
      type: 'step-end',
      name,
      index: __stepIdx__,
      duration: Date.now() - t0,
      screenshot: shot,
      ok: false,
      error: err && err.message,
    });
    throw err;
  } finally {
    __stepIdx__++;
  }
}
`
    : '';

  return `// AUTO-GENERATED by E2E Orchestrator${live ? ' (LIVE PREVIEW)' : ''}
// Case: ${safeName}
// Generated at: ${new Date().toISOString()}

const puppeteer = require('puppeteer');
${liveHelpers}

describe(${JSON.stringify(safeName)}, () => {
  let browser;
  let page;

  beforeAll(async () => {
    browser = await puppeteer.launch(${JSON.stringify(launchOpts)});
    page = await browser.newPage();
    page.setDefaultTimeout(30000);
    page.on('console', (msg) => {
      const type = msg.type();
      if (type === 'error' || type === 'warning') {
        console.log('[browser:' + type + ']', msg.text());
      }
    });
    page.on('pageerror', (err) => console.log('[browser:pageerror]', err.message));
  });

  afterAll(async () => {
    if (browser) await browser.close();
  });

  it('runs end-to-end', async () => {
    const start = Date.now();
    try {
__BODY__
      console.log('[case] done in ' + (Date.now() - start) + 'ms');
    } catch (err) {
      console.log('[case] failed:', err && err.message);
      throw err;
    }
  });
});
`;
}

function sanitizeName(s) {
  return String(s ?? 'untitled').replace(/[^\w\u4e00-\u9fa5\-]+/g, '_').slice(0, 80);
}
